version: '3'
services:
    rabbitmq:
        image: rabbitmq
        ports:
            - "5672:5672"
        networks:
            - flacnet
            - default
        deploy:
            mode: replicated
            replicas: 1
            placement: 
                constraints: [node.role == manager]
    slave:
        image: slave
        ports:
            - "33672:33672"
        networks:
            - flacnet
            - default
        deploy:
            mode: replicated
            replicas: 2
            placement: 
                constraints: [node.role == worker]
        
networks:
    flacnet:
        driver: overlay
