version: '3'
services:
    rabbitmq:
        image: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - flacnet
            - default
        deploy:
            mode: replicated
            replicas: 1
            placement: 
                constraints: [node.role == manager]
    slave:
        image: slave
        networks:
            - flacnet
            - default
        deploy:
            mode: replicated
            replicas: 12
        # placement: 
        #        constraints: [node.role == worker]
                            
networks:
    flacnet:
        driver: overlay
